apiVersion: v1
kind: Secret
metadata:
  name: {{ include "osticket.fullname" . }}-installer
  labels:
    {{- include "osticket.labels" . | nindent 4 }}
stringData:
    OST_NAME: {{ .Values.ostName }}
    OST_EMAIL: {{ .Values.ostEmail }}
    OST_ADMIN_FIRST_NAME: {{ .Values.adminFirstName }}
    OST_ADMIN_LAST_NAME: {{ .Values.adminLastName }}
    OST_ADMIN_EMAIL: {{ .Values.adminEmail }}
    OST_ADMIN_USERNAME: {{ .Values.adminUsername }}
    OST_ADMIN_PASSWORD: {{ .Values.adminPassword }}
    OST_TIMEZONE: {{ .Values.timezone }}
    RELEASE_NAME: {{ include "osticket.fullname" . }}
    MYSQL_ROOT_PASSWORD: {{ .Values.mysql.auth.rootPassword }}
    MYSQL_DB: {{ .Values.mysql.auth.database }}
